### PR TITLE
feat: added network restrictions and improved ui

### PR DESCRIPTION
**Pull request by DannyFung97**

### CODE REVIEW

**Comment by DannyFung97** [comment]
- recreated Table in Soteria Dashboard
- added data field to NetworkConfig to restrict features and app access based on network
- improved lockup tab to be more clear of its functionality

**Comment by DannyFung97** [comment]
- added tooltips to soteria dashboard question icons
- removed cap for input boxes for "DepositForm" and "LockForm" in Staking V2

**Comment by DannyFung97** [comment]
Screenshot (4)
Screenshot (5)

**Comment by dredshep** [comment]
- Low prio: we should remove the red stakingv1 vs stakingv2 for users who don't have v1 funds

Non-blocking observations:

image

- This color change does nothing. It simply removes the old color from the element and possibly makes it transparent. Tailwind already compiled the CSS file and there's no tailwind anymore to create this new color class.

image

- "Harvests rewards for you" is unclear (i.e. "what harvests the rewards?"). Later on we should improve the copy for all clarification boxes.

image

- On hover, we should output the full readable date. Possibly in this format: "Saturday, March 13, 2023, 20:31"

image

- should we rename this function? It says "fromSeconds" but only takes milliseconds.

**Review by dredshep — APPROVED** [review]

**Comment by DannyFung97** [comment]
- renamed `getTimesFromSeconds ` to `getTimesFromMillis`
- hovering over lock time left displays full end date

**Pull request merged**
